export { default as Dota2 } from '@/assets/img/icons/dota2.svg'
export { default as Lol } from '@/assets/img/icons/lol.svg'
export { default as CS2 } from '@/assets/img/icons/cs2.svg'
export { default as Hs } from '@/assets/img/icons/hs.svg'
export { default as Ow } from '@/assets/img/icons/ow.svg'
export { default as Pubg } from '@/assets/img/icons/pubg.svg'
export { default as Fortnite } from '@/assets/img/icons/fortnite.svg'

export { default as IconGift } from '@/assets/img/icons/gift.svg'
export { default as IconCirclecheck } from '@/assets/img/icons/circlecheck.svg'
export { default as IconCircledashed } from '@/assets/img/icons/circledashed.svg'
export { default as IconClock } from '@/assets/img/icons/clock.svg'
export { default as IconEye } from '@/assets/img/icons/eye.svg'
export { default as IconRefresh } from '@/assets/img/icons/refresh.svg'
export { default as IconScore } from '@/assets/img/icons/score.svg'