export { default as Gift } from '@/assets/img/icons/gift.svg'
export { default as Dota2 } from '@/assets/img/icons/dota2.svg'
export { default as Lol } from '@/assets/img/icons/lol.svg'
export { default as CS2 } from '@/assets/img/icons/cs2.svg'
export { default as Hs } from '@/assets/img/icons/hs.svg'
export { default as Ow } from '@/assets/img/icons/ow.svg'
export { default as Pubg } from '@/assets/img/icons/pubg.svg'
export { default as Fortnite } from '@/assets/img/icons/fortnite.svg'